name: Update the domain list

on:
  push:
    branches:
      - master
    paths:
      - uBlacklist.txt

permissions:
  contents: write

jobs:
  generate-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sort uBlacklist.txt
        run: sort uBlacklist.txt -o uBlacklist.txt

      - name: Push generated files
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          if git commit -m "Generate files by GitHub Actions"; then
            git push
          fi
